{"schema_version":"1.7.3","id":"CVE-2021-45115","published":"2022-01-05T00:15:07Z","modified":"2025-10-21T06:40:26.743343Z","aliases":["BIT-django-2021-45115","GHSA-53qw-q765-4fww","PYSEC-2022-1"],"related":["MGASA-2022-0011","RLSA-2022:5498","SUSE-SU-2022:0102-1","SUSE-SU-2022:0103-1","openSUSE-SU-2023:0005-1","openSUSE-SU-2024:11725-1","openSUSE-SU-2024:14208-1","openSUSE-SU-2025:14662-1"],"details":"An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.","affected":[{"ranges":[{"type":"GIT","repo":"https://github.com/django/django","events":[{"introduced":"635d53a86a36cde7866b9caefeb64d809e6bfcd9"},{"fixed":"44e7cca62382f2535ed0f5d2842b433f0bd23a57"}]}],"versions":["2.2","2.2.1","2.2.10","2.2.11","2.2.12","2.2.13","2.2.14","2.2.15","2.2.16","2.2.17","2.2.18","2.2.19","2.2.2","2.2.20","2.2.21","2.2.22","2.2.23","2.2.24","2.2.25","2.2.3","2.2.4","2.2.5","2.2.6","2.2.7","2.2.8","2.2.9"],"database_specific":{"source":"https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-45115.json"}}],"references":[{"type":"FIX","url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"type":"ADVISORY","url":"https://security.netapp.com/advisory/ntap-20220121-0005/"},{"type":"FIX","url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"type":"WEB","url":"https://groups.google.com/forum/#%21forum/django-announce"},{"type":"WEB","url":"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/"}],"severity":[{"type":"CVSS_V3","score":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"}]}