{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-31543.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "8d7b7f6d1c6a741c27ec2215d419c6235556ab0c"
            },
            {
              "last_affected": "a593d27e3d9fcdecc0fbf385ef43116cccad71ec"
            }
          ],
          "repo": "https://github.com/bndr/pipreqs",
          "type": "GIT"
        }
      ],
      "versions": [
        "v0.3.0",
        "v0.3.1",
        "v0.3.2",
        "v0.3.8",
        "v0.4.0",
        "v0.4.1",
        "v0.4.10",
        "v0.4.11",
        "v0.4.2",
        "v0.4.3",
        "v0.4.4",
        "v0.4.5",
        "v0.4.6",
        "v0.4.7",
        "v0.4.8"
      ]
    }
  ],
  "aliases": [
    "GHSA-v4f4-23wc-99mh",
    "PYSEC-2023-99"
  ],
  "details": "A dependency confusion in pipreqs v0.3.0 to v0.4.11 allows attackers to execute arbitrary code via uploading a crafted PyPI package to the chosen repository server.",
  "id": "CVE-2023-31543",
  "modified": "2025-02-19T03:31:50.952621Z",
  "published": "2023-06-30T20:15:09Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/bndr/pipreqs/pull/364"
    },
    {
      "type": "WEB",
      "url": "https://gist.github.com/adeadfed/ccc834440af354a5638f889bee34bafe"
    }
  ],
  "related": [
    "openSUSE-SU-2024:13041-1"
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    }
  ]
}