{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-15240.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "fd3a14f4ccdfbc515d1121d6378ff88bf55a7a7a"
            }
          ],
          "repo": "https://github.com/auth0/omniauth-auth0",
          "type": "GIT"
        }
      ],
      "versions": [
        "v1.4.0",
        "v1.4.1",
        "v1.4.2",
        "v2.0.0",
        "v2.1.0",
        "v2.2.0",
        "v2.3.0",
        "v2.3.1",
        "v2.4.0"
      ]
    }
  ],
  "aliases": [
    "GHSA-58r4-h6v8-jcvm"
  ],
  "details": "omniauth-auth0 (rubygems) versions >= 2.3.0 and < 2.4.1 improperly validate the JWT token signature when using the `jwt_validator.verify` method. Improper validation of the JWT token signature can allow an attacker to bypass authentication and authorization. You are affected by this vulnerability if all of the following conditions apply: 1. You are using `omniauth-auth0`. 2. You are using `JWTValidator.verify` method directly OR you are not authenticating using the SDK\u2019s default Authorization Code Flow. The issue is patched in version 2.4.1.",
  "id": "CVE-2020-15240",
  "modified": "2025-07-01T23:50:57.504428Z",
  "published": "2020-10-21T18:15:12Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/auth0/omniauth-auth0/security/advisories/GHSA-58r4-h6v8-jcvm"
    },
    {
      "type": "WEB",
      "url": "https://rubygems.org/gems/omniauth-auth0"
    },
    {
      "type": "FIX",
      "url": "https://github.com/auth0/omniauth-auth0/commit/fd3a14f4ccdfbc515d1121d6378ff88bf55a7a7a"
    }
  ],
  "related": [
    "GHSA-58r4-h6v8-jcvm"
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
      "type": "CVSS_V3"
    }
  ]
}