{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2022-40314.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "500c131eb49771e36f68d151dfa37fef5a9bc2df"
            },
            {
              "fixed": "33e9b8c3944731e646296d53e71932bed65d2f9e"
            }
          ],
          "repo": "https://github.com/moodle/moodle",
          "type": "GIT"
        }
      ],
      "versions": [
        "v3.9.0",
        "v3.9.1",
        "v3.9.10",
        "v3.9.11",
        "v3.9.12",
        "v3.9.13",
        "v3.9.14",
        "v3.9.15",
        "v3.9.16",
        "v3.9.2",
        "v3.9.3",
        "v3.9.4",
        "v3.9.5",
        "v3.9.6",
        "v3.9.7",
        "v3.9.8",
        "v3.9.9"
      ]
    }
  ],
  "aliases": [
    "BIT-moodle-2022-40314",
    "GHSA-2hmm-q272-xmhf"
  ],
  "details": "A remote code execution risk when restoring backup files originating from Moodle 1.9 was identified.",
  "id": "CVE-2022-40314",
  "modified": "2025-07-29T10:41:12.718058Z",
  "published": "2022-09-30T17:15:13Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2128147"
    },
    {
      "type": "FIX",
      "url": "https://moodle.org/mod/forum/discuss.php?d=438393"
    }
  ],
  "schema_version": "1.7.0",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    }
  ]
}