{"schema_version":"1.7.3","id":"CVE-2023-49080","published":"2023-12-04T21:00:59Z","modified":"2025-10-22T18:40:50.580661Z","aliases":["GHSA-h56g-gq9v-vc8r","PYSEC-2023-272"],"related":["CGA-hh4m-9ffq-7hv5","openSUSE-SU-2024:13489-1"],"summary":"Jupyter Server errors include tracebacks with path information","details":"The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila. Unhandled errors in API requests coming from an authenticated user include traceback information, which can include path information. There is no known mechanism by which to trigger these errors without authentication, so the paths revealed are not considered particularly sensitive, given that the requesting user has arbitrary execution permissions already in the same environment. A fix has been introduced in commit `0056c3aa52` which no longer includes traceback information in JSON error responses. For compatibility, the traceback field is present, but always empty. This commit has been included in version 2.11.2. Users are advised to upgrade. There are no known workarounds for this vulnerability.","affected":[{"ranges":[{"type":"GIT","repo":"https://github.com/jupyter-server/jupyter_server","events":[{"introduced":"0"},{"fixed":"9bd96576c372b4ac14fa769adc780d13e0ed23c1"}]}],"versions":["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.1.0","0.1.1","0.2.0","0.3.0","1.0.0","1.0.0rc1","1.0.0rc10","1.0.0rc11","1.0.0rc12","1.0.0rc13","1.0.0rc14","1.0.0rc15","1.0.0rc16","1.0.0rc2","1.0.0rc3","1.0.0rc4","1.0.0rc5","1.0.0rc6","1.0.0rc7","1.0.0rc8","1.0.0rc9","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.2.0","1.2.1","1.2.2","1.2.3","1.3.0","1.4.0","1.4.1","1.5.0","1.5.1","1.6.0","1.6.1","v1.10.0","v1.10.1","v1.10.2","v1.11.0","v1.11.1","v1.11.2","v1.12.0","v1.12.1","v1.13.0","v1.13.1","v1.13.2","v1.13.3","v1.13.4","v1.13.5","v1.15.0","v1.15.1","v1.15.2","v1.15.3","v1.15.4","v1.15.5","v1.15.6","v1.16.0","v1.6.2","v1.6.3","v1.6.4","v1.7.0","v1.7.0a0","v1.7.0a1","v1.7.0a2","v1.8.0","v1.9.0","v2.0.0","v2.0.0a0","v2.0.0a1","v2.0.0a2","v2.0.0b0","v2.0.0b1","v2.0.0rc0","v2.0.0rc1","v2.0.0rc2","v2.0.0rc3","v2.0.0rc4","v2.0.0rc5","v2.0.0rc6","v2.0.0rc7","v2.0.0rc8","v2.0.1","v2.0.2","v2.0.3","v2.0.4","v2.0.5","v2.0.6","v2.0.7","v2.1.0","v2.10.0","v2.10.1","v2.11.0","v2.11.1","v2.2.0","v2.2.1","v2.3.0","v2.4.0","v2.5.0","v2.6.0","v2.7.0","v2.7.1","v2.7.2","v2.7.3","v2.8.0","v2.9.0","v2.9.1"],"database_specific":{"source":"https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-49080.json"}}],"references":[{"type":"ADVISORY","url":"https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-h56g-gq9v-vc8r"},{"type":"FIX","url":"https://github.com/jupyter-server/jupyter_server/commit/0056c3aa52cbb28b263a7a609ae5f17618b36652"},{"type":"WEB","url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/62LO7PPIAMLIDEKUOORXLHKLGA6QPL77/"},{"type":"WEB","url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FG2JWZI5KPUYMDPS53AIFTZJWZD3IT6I/"}],"database_specific":{"cwe_ids":["CWE-209"]},"severity":[{"type":"CVSS_V3","score":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N"}]}