{"schema_version":"1.7.3","id":"CVE-2022-35940","published":"2022-09-16T19:45:20Z","modified":"2025-10-22T18:35:43.311609Z","aliases":["BIT-tensorflow-2022-35940","GHSA-x989-q2pq-4q5x"],"related":["openSUSE-SU-2024:12355-1"],"summary":"Int overflow in `RaggedRangeOp` in Tensoflow","details":"TensorFlow is an open source platform for machine learning. The `RaggedRangOp` function takes an argument `limits` that is eventually used to construct a `TensorShape` as an `int64`. If `limits` is a very large float, it can overflow when converted to an `int64`. This triggers an `InvalidArgument` but also throws an abort signal that crashes the program. We have patched the issue in GitHub commit 37cefa91bee4eace55715eeef43720b958a01192. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.","affected":[{"ranges":[{"type":"GIT","repo":"https://github.com/tensorflow/tensorflow","events":[{"introduced":"0"},{"fixed":"dd7b8a3c1714d0052ce4b4a2fd8dcef927439a24"}]},{"type":"GIT","repo":"https://github.com/tensorflow/tensorflow","events":[{"introduced":"3f878cff5b698b82eea85db2b60d65a2e320850e"},{"fixed":"0516d4d8bced506cae97dc3cb45dbd2fe4311f26"}]},{"type":"GIT","repo":"https://github.com/tensorflow/tensorflow","events":[{"introduced":"8a20d54a3c1bfa38c03ea99a2ad3c1b0a45dfa95"},{"fixed":"d8ce9f9c301d021a69953134185ab728c1c248d3"}]}],"versions":["0.12.0-rc0","0.12.0-rc1","0.12.1","0.5.0","0.6.0","v0.10.0","v0.10.0rc0","v0.11.0","v0.11.0rc0","v0.11.0rc1","v0.11.0rc2","v0.12.0","v0.7.0","v0.7.1","v0.8.0rc0","v0.9.0","v0.9.0rc0","v1.0.0","v1.0.0-alpha","v1.0.0-rc0","v1.0.0-rc1","v1.0.0-rc2","v1.1.0","v1.1.0-rc0","v1.1.0-rc1","v1.1.0-rc2","v1.12.0","v1.12.0-rc0","v1.12.0-rc1","v1.12.0-rc2","v1.12.1","v1.2.0","v1.2.0-rc0","v1.2.0-rc1","v1.2.0-rc2","v1.3.0-rc0","v1.3.0-rc1","v1.5.0","v1.5.0-rc0","v1.5.0-rc1","v1.6.0","v1.6.0-rc0","v1.6.0-rc1","v1.7.0","v1.7.0-rc0","v1.7.0-rc1","v1.8.0","v1.8.0-rc0","v1.8.0-rc1","v1.9.0","v1.9.0-rc0","v1.9.0-rc1","v1.9.0-rc2","v2.7.0","v2.7.0-rc0","v2.7.0-rc1","v2.7.1","v2.8.0","v2.9.0"],"database_specific":{"source":"https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2022-35940.json"}}],"references":[{"type":"ADVISORY","url":"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-x989-q2pq-4q5x"},{"type":"FIX","url":"https://github.com/tensorflow/tensorflow/commit/37cefa91bee4eace55715eeef43720b958a01192"},{"type":"WEB","url":"https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/ragged_range_op.cc#L74-L88"}],"database_specific":{"cwe_ids":["CWE-190"]},"severity":[{"type":"CVSS_V3","score":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"}]}