{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-15585.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "1f2e6f3f6d84b8eab5526acdd69c38f5b78c3b0e"
            },
            {
              "fixed": "44b9ff8bbc5170913ca4e859b7c29bd415db38ee"
            }
          ],
          "repo": "https://gitlab.com/gitlab-org/gitlab",
          "type": "GIT"
        }
      ],
      "versions": [
        "v12.1.0-ee",
        "v12.1.1-ee",
        "v12.1.10-ee",
        "v12.1.11-ee",
        "v12.1.2-ee",
        "v12.1.3-ee",
        "v12.1.4-ee",
        "v12.1.6-ee",
        "v12.1.8-ee",
        "v12.1.9-ee"
      ]
    }
  ],
  "details": "Improper authentication exists in < 12.3.2, < 12.2.6, and < 12.1.12 for GitLab Community Edition (CE) and Enterprise Edition (EE) in the GitLab SAML integration had a validation issue that permitted an attacker to takeover another user's account.",
  "id": "CVE-2019-15585",
  "modified": "2025-08-16T05:36:50.569929Z",
  "published": "2020-01-28T03:15:10Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://about.gitlab.com/blog/2019/09/30/security-release-gitlab-12-dot-3-dot-2-released/"
    },
    {
      "type": "WEB",
      "url": "https://hackerone.com/reports/471323"
    }
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    }
  ]
}