{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2017-8031.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "8c5ccff535f9fb3b924a3d1c52f795b0f8242054"
            },
            {
              "fixed": "47fe67cb5e95fe976deccbea73c1749cc1323e1d"
            }
          ],
          "repo": "https://github.com/cloudfoundry/uaa-release",
          "type": "GIT"
        }
      ],
      "versions": [
        "v30",
        "v30.1",
        "v30.2",
        "v30.3",
        "v30.4",
        "v30.5"
      ]
    }
  ],
  "aliases": [
    "GHSA-j4p3-2m2h-cv5f"
  ],
  "details": "An issue was discovered in Cloud Foundry Foundation cf-release (all versions prior to v279) and UAA (30.x versions prior to 30.6, 45.x versions prior to 45.4, 52.x versions prior to 52.1). In some cases, the UAA allows an authenticated user for a particular client to revoke client tokens for other users on the same client. This occurs only if the client is using opaque tokens or JWT tokens validated using the check_token endpoint. A malicious actor could cause denial of service.",
  "id": "CVE-2017-8031",
  "modified": "2025-10-21T04:21:44.028716Z",
  "published": "2017-11-27T10:29:00Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "http://www.securityfocus.com/bid/101967"
    },
    {
      "type": "REPORT",
      "url": "https://www.cloudfoundry.org/cve-2017-8031/"
    }
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "type": "CVSS_V3"
    }
  ]
}