{
  "affected": [
    {
      "database_specific": {
        "source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2025-49604.json"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "52aac0dd423cbb11a013711c8e1c3004adf31ef8"
            }
          ],
          "repo": "https://github.com/ameba-aiot/ameba-arduino-d",
          "type": "GIT"
        }
      ],
      "versions": [
        "V3.0.10-v02",
        "V3.0.11",
        "V3.0.5",
        "V3.0.6",
        "V3.0.7",
        "V3.0.8-V04",
        "V3.0.9",
        "V3.1.0",
        "V3.1.1",
        "V3.1.3",
        "V3.1.4",
        "V3.1.5",
        "V3.1.6",
        "V3.1.6-V02",
        "V3.1.7",
        "V3.1.8"
      ]
    }
  ],
  "details": "Rejected reason: DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.",
  "id": "CVE-2025-49604",
  "modified": "2025-07-22T16:44:35.087415Z",
  "published": "2025-07-09T16:15:24Z",
  "schema_version": "1.7.0",
  "withdrawn": "2025-07-23T09:57:45.754014Z"
}