{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/google/oss-fuzz-vulns/blob/main/vulns/php/OSV-2021-1759.yaml"
      },
      "ecosystem_specific": {
        "severity": "HIGH"
      },
      "package": {
        "ecosystem": "OSS-Fuzz",
        "name": "php",
        "purl": "pkg:generic/php"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "97cdf62a6a1d8491f8d1ef1580f344400eb51f1d"
            },
            {
              "introduced": "713dcb28181895d241e6dbe63f63ee654ba757b4"
            },
            {
              "fixed": "eee3b1d917591e5106aef9fd4fe93393e95fc13d"
            }
          ],
          "repo": "https://github.com/php/php-src.git",
          "type": "GIT"
        }
      ],
      "versions": [
        "php-8.1.2RC1",
        "php-8.1.3",
        "php-8.1.4RC1",
        "php-8.1.7RC1"
      ]
    }
  ],
  "details": "OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42894\n\n```\nCrash type: Heap-use-after-free READ 4\nCrash state:\nzend_hash_reverse_apply\nshutdown_destructors\nzend_call_destructors\n```\n",
  "id": "OSV-2021-1759",
  "modified": "2023-02-24T04:23:14.413547Z",
  "published": "2021-12-25T00:02:02.853767Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42894"
    }
  ],
  "schema_version": "1.7.3",
  "summary": "Heap-use-after-free in zend_hash_reverse_apply"
}